use crate::map::*;
use std::collections::HashMap;

lazy_static! {
    pub static ref ROOMS: HashMap<String, Room> = {
        let mut rooms = HashMap::new();
        rooms.insert(
            String::from("1-3"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 6, 17),
                    pt(0, 7, 2),
                    pt(1, 5, 34),
                    pt(1, 6, 20),
                    pt(1, 7, 17),
                    pt(2, 2, 44),
                    pt(2, 6, 34),
                    pt(3, 1, 44),
                    pt(4, 3, 35),
                    pt(6, 1, 44),
                    pt(7, 2, 44),
                    pt(7, 6, 34),
                    pt(8, 5, 34),
                    pt(8, 6, 19),
                    pt(8, 7, 18),
                ],
            ),
        );

        rooms.insert(
            String::from("1-5"),
            Room::new(
                WallShape(true, true, true, true),
                5,
                vec![
                    pt(0, 0, 2),
                    pt(0, 1, 15),
                    pt(0, 6, 17),
                    pt(0, 7, 2),
                    pt(1, 0, 15),
                    pt(1, 1, 22),
                    pt(1, 6, 20),
                    pt(1, 7, 17),
                    pt(2, 1, 0),
                    pt(2, 2, 42),
                    pt(2, 5, 43),
                    pt(2, 6, 0),
                    pt(3, 3, 35),
                    ln(3, 1, 42, 84),
                    ln(3, 6, 43, 84),
                    ln(7, 1, 0, 82),
                    ln(7, 2, 42, 82),
                    ln(7, 5, 43, 82),
                    ln(7, 6, 0, 82),
                    ln(1, 2, 0, 94),
                ],
            ),
        );

        rooms.insert(
            String::from("1-7"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(1, 1, 34),
                    pt(1, 6, 34),
                    pt(2, 3, 5),
                    pt(3, 3, 35),
                    pt(5, 1, 34),
                    pt(5, 6, 34),
                    pt(6, 0, 16),
                    pt(6, 1, 10),
                    pt(6, 2, 21),
                    pt(6, 5, 19),
                    pt(6, 6, 10),
                    pt(6, 7, 18),
                    ln(2, 2, 5, 83),
                    ln(2, 4, 5, 83),
                    ln(7, 0, 2, 83),
                    ln(7, 1, 2, 83),
                    ln(7, 2, 7, 82),
                    ln(7, 5, 8, 82),
                    ln(7, 6, 2, 83),
                    ln(7, 7, 2, 83),
                    ln(4, 3, 5, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("2-3"),
            Room::new(
                WallShape(true, false, true, true),
                4,
                vec![
                    pt(0, 2, 26),
                    pt(1, 1, 34),
                    pt(1, 3, 5),
                    pt(1, 5, 51),
                    pt(1, 6, 34),
                    pt(2, 3, 32),
                    pt(4, 2, 32),
                    pt(4, 7, 29),
                    pt(5, 2, 5),
                    pt(5, 3, 32),
                    pt(6, 2, 32),
                    pt(6, 3, 5),
                    pt(7, 3, 32),
                    ln(1, 2, 5, 83),
                    ln(2, 5, 44, 82),
                    ln(3, 3, 5, 82),
                    ln(4, 5, 51, 86),
                    ln(4, 6, 5, 86),
                    ln(7, 2, 5, 83),
                    ln(8, 3, 5, 82),
                ],
            ),
        );

        rooms.insert(
            String::from("2-4"),
            Room::new(
                WallShape(true, false, false, true),
                4,
                vec![
                    pt(0, 1, 2),
                    pt(0, 2, 15),
                    pt(1, 1, 15),
                    pt(1, 2, 22),
                    pt(1, 6, 34),
                    pt(2, 0, 15),
                    pt(2, 1, 22),
                    pt(2, 2, 44),
                    pt(2, 4, 32),
                    pt(3, 6, 37),
                    pt(4, 0, 27),
                    pt(6, 0, 7),
                    pt(6, 6, 37),
                    pt(7, 0, 16),
                    pt(7, 4, 21),
                    pt(8, 0, 55),
                    pt(8, 3, 58),
                    pt(8, 6, 19),
                    pt(8, 7, 10),
                    ln(0, 0, 2, 82),
                    ln(6, 5, 42, 84),
                    ln(8, 4, 7, 82),
                    ln(6, 1, 0, 94),
                    ln(7, 1, 10, 93),
                    ln(8, 1, 54, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("2-5"),
            Room::new(
                WallShape(false, false, true, true),
                4,
                vec![
                    pt(0, 4, 13),
                    pt(1, 5, 43),
                    pt(2, 3, 43),
                    pt(2, 4, 42),
                    pt(4, 7, 4),
                    pt(5, 7, 8),
                    pt(7, 3, 43),
                    pt(7, 4, 42),
                    pt(8, 0, 10),
                    pt(8, 1, 21),
                    pt(8, 2, 35),
                    ln(2, 6, 43, 82),
                    ln(4, 6, 6, 82),
                    ln(6, 6, 43, 83),
                    ln(3, 1, 37, 92),
                    ln(6, 1, 37, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("2-6"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 0, 2),
                    pt(0, 1, 15),
                    pt(0, 6, 17),
                    pt(0, 7, 2),
                    pt(1, 0, 15),
                    pt(1, 1, 22),
                    pt(1, 2, 6),
                    pt(1, 5, 6),
                    pt(1, 6, 20),
                    pt(1, 7, 17),
                    pt(4, 0, 4),
                    pt(5, 0, 7),
                    pt(8, 0, 16),
                    pt(8, 1, 21),
                    pt(8, 2, 6),
                    pt(8, 5, 6),
                    pt(8, 6, 19),
                    pt(8, 7, 18),
                    ln(2, 1, 6, 82),
                    ln(2, 6, 6, 82),
                    ln(6, 1, 6, 82),
                    ln(6, 6, 6, 82),
                    ln(3, 3, 37, 92),
                    ln(6, 3, 37, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("2-7"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 0, 2),
                    pt(0, 1, 15),
                    pt(0, 3, 4),
                    pt(0, 4, 9),
                    pt(0, 6, 17),
                    pt(0, 7, 2),
                    pt(1, 0, 15),
                    pt(1, 1, 22),
                    pt(1, 2, 42),
                    pt(1, 5, 43),
                    pt(1, 6, 20),
                    pt(1, 7, 17),
                    pt(2, 3, 5),
                    pt(8, 0, 16),
                    pt(8, 1, 21),
                    pt(8, 2, 42),
                    pt(8, 5, 43),
                    pt(8, 6, 19),
                    pt(8, 7, 18),
                    ln(2, 1, 42, 86),
                    ln(2, 6, 43, 86),
                ],
            ),
        );

        rooms.insert(
            String::from("3-4"),
            Room::new(
                WallShape(false, true, false, false),
                4,
                vec![
                    pt(0, 0, 51),
                    pt(0, 3, 53),
                    pt(0, 6, 8),
                    pt(0, 7, 2),
                    pt(1, 2, 50),
                    pt(1, 3, 57),
                    pt(1, 6, 20),
                    pt(1, 7, 9),
                    pt(2, 3, 15),
                    pt(2, 4, 22),
                    pt(3, 4, 0),
                    pt(4, 1, 35),
                    pt(4, 4, 42),
                    pt(5, 4, 0),
                    pt(6, 3, 16),
                    pt(6, 4, 21),
                    pt(7, 2, 49),
                    pt(7, 3, 58),
                    ln(0, 4, 7, 82),
                    ln(0, 5, 42, 84),
                    ln(1, 0, 34, 82),
                    ln(2, 2, 53, 85),
                    ln(3, 0, 51, 83),
                    ln(3, 3, 7, 83),
                    ln(5, 5, 42, 84),
                    ln(6, 0, 34, 82),
                    ln(7, 4, 7, 82),
                    ln(8, 0, 51, 82),
                    ln(8, 3, 53, 82),
                ],
            ),
        );

        rooms.insert(
            String::from("3-5"),
            Room::new(
                WallShape(false, true, true, false),
                4,
                vec![
                    pt(0, 0, 2),
                    pt(0, 1, 7),
                    pt(1, 0, 9),
                    pt(1, 1, 22),
                    pt(3, 2, 5),
                    pt(4, 2, 35),
                    pt(4, 5, 32),
                    pt(7, 2, 32),
                    pt(7, 5, 32),
                    ln(3, 1, 5, 83),
                    ln(3, 3, 5, 83),
                    ln(5, 2, 5, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("3-6"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 3, 4),
                    pt(0, 4, 9),
                    pt(1, 6, 34),
                    pt(3, 2, 43),
                    pt(3, 3, 0),
                    pt(3, 4, 42),
                    pt(3, 7, 20),
                    pt(5, 3, 59),
                    pt(6, 2, 43),
                    pt(6, 3, 0),
                    pt(6, 4, 42),
                    pt(6, 7, 19),
                    pt(8, 2, 35),
                    pt(8, 6, 34),
                    ln(4, 4, 44, 82),
                    ln(4, 7, 4, 82),
                ],
            ),
        );

        rooms.insert(
            String::from("3-7"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 2, 22),
                    pt(0, 5, 20),
                    pt(1, 1, 34),
                    pt(1, 6, 34),
                    pt(3, 0, 22),
                    pt(3, 2, 37),
                    pt(3, 7, 20),
                    pt(6, 0, 21),
                    pt(6, 7, 19),
                    pt(8, 1, 34),
                    pt(8, 6, 34),
                    ln(2, 1, 5, 86),
                    ln(2, 6, 5, 86),
                    ln(4, 0, 4, 82),
                    ln(4, 7, 5, 82),
                    ln(6, 2, 37, 82),
                    ln(0, 3, 4, 92),
                    ln(1, 2, 5, 94),
                    ln(2, 2, 37, 93),
                    ln(7, 3, 37, 92),
                    ln(8, 2, 5, 94),
                ],
            ),
        );

        rooms.insert(
            String::from("4-4"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 4, 15),
                    pt(1, 4, 7),
                    pt(2, 4, 38),
                    pt(2, 5, 33),
                    pt(3, 0, 56),
                    pt(3, 3, 57),
                    pt(3, 4, 7),
                    pt(4, 0, 15),
                    pt(4, 4, 22),
                    pt(5, 4, 43),
                    pt(5, 5, 0),
                    pt(5, 6, 42),
                    pt(6, 7, 20),
                    pt(7, 7, 4),
                    pt(8, 0, 16),
                    pt(8, 1, 21),
                    pt(8, 7, 19),
                    ln(0, 0, 51, 83),
                    ln(0, 3, 53, 82),
                    ln(0, 1, 4, 92),
                    ln(3, 1, 52, 92),
                    ln(4, 1, 9, 93),
                ],
            ),
        );

        rooms.insert(
            String::from("4-5"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 1, 22),
                    pt(0, 2, 4),
                    pt(0, 6, 20),
                    pt(4, 7, 8),
                    pt(5, 7, 25),
                    pt(6, 0, 22),
                    pt(7, 0, 4),
                    pt(8, 0, 21),
                    ln(0, 3, 32, 84),
                    ln(3, 2, 32, 86),
                    ln(0, 4, 4, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("4-6"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 2, 22),
                    pt(0, 5, 20),
                    pt(1, 1, 0),
                    pt(1, 2, 42),
                    pt(1, 5, 43),
                    pt(1, 6, 0),
                    pt(3, 1, 34),
                    pt(3, 5, 37),
                    pt(4, 0, 7),
                    pt(5, 0, 23),
                    pt(6, 1, 34),
                    pt(6, 5, 37),
                    pt(8, 2, 35),
                    ln(3, 2, 5, 84),
                    ln(3, 3, 5, 84),
                    ln(3, 4, 5, 84),
                    ln(0, 3, 4, 92),
                    ln(4, 1, 5, 95),
                    ln(5, 1, 5, 95),
                ],
            ),
        );

        rooms.insert(
            String::from("5-4"),
            Room::new(
                WallShape(true, true, true, true),
                5,
                vec![
                    pt(0, 0, 2),
                    pt(0, 1, 15),
                    pt(0, 6, 17),
                    pt(0, 7, 2),
                    pt(1, 0, 15),
                    pt(1, 1, 22),
                    pt(1, 2, 34),
                    pt(1, 6, 20),
                    pt(1, 7, 17),
                    pt(3, 7, 20),
                    pt(6, 7, 19),
                    pt(8, 0, 16),
                    pt(8, 1, 21),
                    pt(8, 2, 35),
                    pt(8, 6, 19),
                    pt(8, 7, 18),
                    ln(4, 7, 4, 82),
                ],
            ),
        );

        rooms.insert(
            String::from("5-5"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(0, 4, 30),
                    pt(3, 0, 22),
                    pt(3, 3, 19),
                    pt(3, 4, 21),
                    pt(4, 3, 8),
                    pt(4, 4, 7),
                    pt(5, 3, 20),
                    pt(5, 4, 22),
                    pt(6, 0, 21),
                    pt(7, 2, 43),
                    pt(7, 5, 42),
                    pt(8, 2, 44),
                    pt(8, 5, 44),
                    ln(4, 0, 4, 82),
                    ln(7, 3, 0, 92),
                ],
            ),
        );

        rooms.insert(
            String::from("6-2"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(1, 1, 34),
                    pt(1, 6, 34),
                    pt(2, 0, 16),
                    pt(2, 4, 21),
                    pt(3, 0, 21),
                    pt(3, 1, 37),
                    pt(3, 3, 37),
                    pt(3, 4, 7),
                    pt(5, 7, 25),
                    pt(6, 0, 22),
                    pt(6, 1, 37),
                    pt(6, 3, 37),
                    pt(6, 4, 7),
                    pt(7, 0, 15),
                    pt(7, 4, 22),
                    pt(8, 1, 34),
                    pt(8, 6, 34),
                    ln(3, 2, 5, 84),
                    ln(4, 4, 38, 82),
                    ln(4, 5, 5, 82),
                    ln(4, 6, 5, 82),
                    ln(2, 1, 10, 93),
                    ln(4, 1, 5, 93),
                    ln(5, 1, 5, 93),
                    ln(7, 1, 9, 93),
                ],
            ),
        );

        rooms.insert(
            String::from("6-3"),
            Room::new(
                WallShape(true, true, true, true),
                5,
                vec![
                    pt(1, 1, 43),
                    pt(1, 6, 42),
                    pt(2, 1, 44),
                    pt(2, 6, 44),
                    pt(5, 0, 4),
                    pt(5, 7, 4),
                    pt(7, 1, 44),
                    pt(7, 6, 44),
                    pt(8, 1, 43),
                    pt(8, 6, 42),
                    ln(1, 2, 0, 94),
                    ln(8, 2, 0, 94),
                ],
            ),
        );

        rooms.insert(
            String::from("6-4"),
            Room::new(
                WallShape(true, true, true, true),
                4,
                vec![
                    pt(3, 3, 34),
                    pt(5, 0, 31),
                    pt(5, 7, 4),
                    pt(6, 3, 34),
                    ln(3, 4, 37, 84),
                ],
            ),
        );

        rooms.insert(
            String::from("6-5"),
            Room::new(
                WallShape(true, true, true, true),
                5,
                vec![pt(0, 4, 4), pt(5, 0, 4)],
            ),
        );
        rooms
    };
}
